# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Renaming ? Change the README badge.
name: Build
on:
  push:
    branches:
      - master
  pull_request:
env:
  TRAVIS: true
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform base checks
        run: ./gradlew demo:assembleDebug lib:javadoc
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [22, 25, 28]
        include:
          - EMULATOR_API: 28
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 25
            EMULATOR_ARCH: x86
          - EMULATOR_API: 22
            EMULATOR_ARCH: x86
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.2.0
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          emulator-build: 6031357
          script: ./.github/workflows/emulator_script.sh
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          path: ./lib/build/outputs/code_coverage/debugAndroidTest/connected