# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Perform base checks
        run: ./gradlew demo:assembleDebug lib:deployLocal
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [23, 25, 29]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          script: ./.github/workflows/emulator_script.sh

      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v4
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          path: ./lib/build/reports/androidTests/connected/debug/